# =======================================================
# Care Voice 簡化統一部署配置
# 使用單一 multi-stage Dockerfile 構建
# =======================================================
version: '3.8'

services:
  # =======================================================
  # 主要服務: Care Voice 統一整合服務
  # =======================================================
  care-voice:
    build:
      context: .
      dockerfile: Dockerfile.unified
    image: care-voice-unified:latest
    container_name: care-voice-integrated
    
    # 端口映射
    ports:
      - "8000:8000"
    
    # 重啟策略
    restart: unless-stopped
    
    # 環境變數
    environment:
      - RUST_LOG=info
      - TZ=Asia/Taipei
      - NGINX_PORT=8000
      - BACKEND_PORT=8001
    
    # 健康檢查
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 持久化儲存
    volumes:
      - care-voice-logs:/var/log/supervisor
      - care-voice-nginx-logs:/var/log/nginx
      - care-voice-app-logs:/var/log/care-voice
    
    # 網路配置
    networks:
      - care-voice-net
    
    # 標籤和元數據
    labels:
      - "care-voice.service=unified"
      - "care-voice.version=1.0.0"
      - "care-voice.component=integrated"
      - "care-voice.architecture=multi-stage"
    
    # 資源限制
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

  # =======================================================
  # 可選: 開發模式前端服務 (僅開發時啟用)
  # =======================================================
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: care-voice-frontend-dev
    
    # 僅在開發模式啟用
    profiles: ["dev"]
    
    ports:
      - "3000:3000"
    
    # 開發模式配置
    environment:
      - NODE_ENV=development
    
    # 代碼熱重載
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/package.json:/app/package.json:ro
    
    networks:
      - care-voice-net

  # =======================================================
  # 可選: 後端開發服務 (僅開發時啟用)
  # =======================================================
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: care-voice-backend-dev
    
    # 僅在開發模式啟用
    profiles: ["dev"]
    
    ports:
      - "8001:8000"
    
    # 開發模式配置
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    
    # 代碼重載 (需要配置文件監控)
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/Cargo.toml:/app/Cargo.toml:ro
    
    networks:
      - care-voice-net

# =======================================================
# 持久化儲存配置
# =======================================================
volumes:
  # 應用日誌
  care-voice-logs:
    driver: local
    labels:
      - "care-voice.volume=supervisor-logs"
  
  # nginx 日誌
  care-voice-nginx-logs:
    driver: local
    labels:
      - "care-voice.volume=nginx-logs"
  
  # 應用專用日誌
  care-voice-app-logs:
    driver: local
    labels:
      - "care-voice.volume=app-logs"
  
  # 可選: 數據持久化
  care-voice-data:
    driver: local
    labels:
      - "care-voice.volume=data"

# =======================================================
# 網路配置
# =======================================================
networks:
  care-voice-net:
    driver: bridge
    name: care-voice-network
    labels:
      - "care-voice.network=main"
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

# =======================================================
# 擴展配置 (可選功能)
# =======================================================
x-common-variables: &common-env
  RUST_LOG: info
  TZ: Asia/Taipei

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-restart-policy: &restart-unless-stopped
  restart: unless-stopped